
obj-y += mt_dcm.o
obj-y	+= mtcmos.o
obj-$(CONFIG_MTK_PSCI)	+= mt_psci.o
obj-y += mt_hotplug_strategy_main.o mt_hotplug_strategy_core.o mt_hotplug_strategy_procfs.o mt_hotplug_strategy_cpu.o mt_hotplug_strategy_api.o mt_hotplug_strategy_algo.o
